// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57Zif6uUWlZw5162gC-ab7k9WEoJ_I9g',
    appId: '1:733835310780:web:3414fa3a6584de4337c2b9',
    messagingSenderId: '733835310780',
    projectId: 'fitplanai-bd88c',
    authDomain: 'fitplanai-bd88c.firebaseapp.com',
    storageBucket: 'fitplanai-bd88c.firebasestorage.app',
    measurementId: 'G-3FKDHEFNJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0RADcKQnYh3jwiZl4xmhN93r1S0E8PM',
    appId: '1:733835310780:android:b4d50f5d0eb6863f37c2b9',
    messagingSenderId: '733835310780',
    projectId: 'fitplanai-bd88c',
    storageBucket: 'fitplanai-bd88c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzi0MfJBrvO_MaaozAJA2_JLXf8sPsiI',
    appId: '1:733835310780:ios:e4ae46702a737d5b37c2b9',
    messagingSenderId: '733835310780',
    projectId: 'fitplanai-bd88c',
    storageBucket: 'fitplanai-bd88c.firebasestorage.app',
    iosClientId: '733835310780-7v4vbf663rc4k8h3jgu5g86q7svd046u.apps.googleusercontent.com',
    iosBundleId: 'com.fitplanai.fitplanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzi0MfJBrvO_MaaozAJA2_JLXf8sPsiI',
    appId: '1:733835310780:ios:e4ae46702a737d5b37c2b9',
    messagingSenderId: '733835310780',
    projectId: 'fitplanai-bd88c',
    storageBucket: 'fitplanai-bd88c.firebasestorage.app',
    iosClientId: '733835310780-7v4vbf663rc4k8h3jgu5g86q7svd046u.apps.googleusercontent.com',
    iosBundleId: 'com.fitplanai.fitplanAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57Zif6uUWlZw5162gC-ab7k9WEoJ_I9g',
    appId: '1:733835310780:web:35ff7a5a406259a037c2b9',
    messagingSenderId: '733835310780',
    projectId: 'fitplanai-bd88c',
    authDomain: 'fitplanai-bd88c.firebaseapp.com',
    storageBucket: 'fitplanai-bd88c.firebasestorage.app',
    measurementId: 'G-G9S59V9MN3',
  );

}